Karletty
RonaldNolascoU/smart-hydro-heat pull request #35
Opened 2023-09-26 04:05 UTC by Karletty

Pantalla del Registro y de Notificaciones

2023-09-27 03:04 UTC, Victor-Rodriguez commented on src/screens/NotificationsScreen.jsx
-El contenido del componente NotificationsScreen.jsx debe ser definido en un archivo aparte con un nombre acorde al componente, al igual que se hizo con el componente Register.jsx.

-Se debe separar el estilo del componente en su propio archivo con formato NombreComponente.styles.jsx

-En el archivo NotificationsScreen.jsx solo debe tener la llamada al componente, al igual que se hizo con el archivo RegisterScreen.jsx el cual solo manda a llamar al componente Resgister.jsx

2023-09-27 03:05 UTC, Victor-Rodriguez requested changes
Revisar cambios solicitados

2023-09-27 16:47 UTC, Karletty commented on src/screens/NotificationsScreen.jsx
Cambios solicitados realizados

2023-09-28 05:55 UTC, edwinmejia-123 reviewed
- Instanciar el useState o eliminar la variable
- Llenar con datos quemados las notificaciones para tener un ejemplo de como funciona

2023-09-28 05:55 UTC, edwinmejia-123 commented on src/components/Notifications/Notification.jsx
> +    const [notifications, setNotifications] = useState([]);
Puedes eliminar esta constante porque no se utiliza, además da error porque no hemos instanciado el useState.

2023-09-28 05:55 UTC, edwinmejia-123 commented on src/components/Notifications/Notification.jsx
> +            {notifications.map((notification, i) =>
Si ocupas la variable, puedes llenarla con el archivo de prueba que creaste por favor y corregir el error anterior

2023-10-04 16:08 UTC, edwinmejia-123 approved these changes

2023-10-04 16:08 UTC, edwinmejia-123 commented on src/components/Notifications/Notification.jsx
>  import React from "react";
Importar UseState, ejempo 'import React, {useState} from "react"'

2023-10-04 16:08 UTC, edwinmejia-123 commented on src/components/Notifications/Notification.jsx
> +import notificationExample from "./notificationTest"
importar correctamente el componente, la funcion exportada del archivo es **_testNotifications_** entonces quedaria asi
```javascript
import { testNotifications } from "./notificationTest"
``` 
Porque no es la funcion por defecto

2023-10-04 16:08 UTC, edwinmejia-123 commented on src/components/Notifications/Notification.jsx
>          <View>
Ocupemos un **ScrollView** de la dependencia react-native para que puedan verse todas las notificaciones de mejor manera. 
Puedes ver el componente `Home.jsx` como ejemplo por favor

2023-10-04 16:14 UTC, Victor-Rodriguez approved these changes

2023-10-04 16:15 UTC, merged