Notificaciones api
RonaldNolascoU/smart-hydro-heat pull request #46
Opened 2023-11-13 00:49 UTC by Karletty

2023-11-13 03:48 UTC, RonaldNolascoU requested changes

2023-11-13 03:48 UTC, RonaldNolascoU commented on google-services.json
@Karletty Este archivo no debe ir subido a git. Por favor removerlo

`git rebase -i HEAD~1`

Al commit donde subiste este archivo, cambiar `pick` por `drop` y guardar

Luego: `git push origin Karletty-notificaciones-api --force`

Estos comandos eliminan del historial de git todo rastro de que se subió este archivo

2023-11-13 04:10 UTC, Karletty commented on google-services.json
Ya lo corregí

2023-11-14 03:06 UTC, Victor-Rodriguez approved these changes

2023-11-14 06:51 UTC, edwinmejia-123 approved these changes

2023-11-14 12:10 UTC, RonaldNolascoU approved these changes

2023-11-14 12:10 UTC, merged